### ISSUE TITLE
Meanwhile, I'm confused here... (Solved)

### ISSUE THREAD

**Issue by nazimboudeffa** [MightyChubz/Thunder-Engine#1]
Hi Chubz it's me, check the last chat phrase here and i am going to see how i can fix that

```
15:15don1ruillhi
15:16don1ruilldoing not bad ;p
kay0313 joined the room.
15:25don1ruillthis is awsome
15:25don1ruillload, update, render
15:25don1ruillfor me load is draw in HTML canvas
15:27don1ruillhere it goes, pen is the Gimp, so drawing doesn't make sense to the designer
15:27don1ruill;p
sl0wturtle joined the room.
amelica-red joined the room.
pjpartridge joined the room.
15:29don1ruillit's 100 okey
15:29don1ruillso yeah
15:29don1ruillticks
15:30don1ruillhe sent me propositions for teeshirts
15:30don1ruilllol
15:32don1ruillwatchers ...
15:32don1ruillimage ...
15:32don1ruilltruth ...
15:33don1ruillwithout hurting any gov accords, it makes sense also without making people crazy about code
15:33don1ruill;)
15:34don1ruillalso without going back so far in the past to define what is internet basically
torres joined the room.
15:38defnullo.o
15:39don1ruillhere it is
15:39don1ruilli must take time to understand this
15:40don1ruillthis is what is terrible man !
15:40studentprogr...hellur people
15:40don1ruillyo @drmjg
15:41chubz@drmjg: Wasup man
narror joined the room.
15:41studentprogr...good hope u r doing well
15:41don1ruillyo yo
15:42don1ruillyea it's like both 2D and 3D but it still make confusion
15:43don1ruilltextures
15:43don1ruill3Diso
15:43don1ruill3dIsometrics
15:44don1ruill:/
drmjg joined the room.
15:44don1ruilluntil you start to make links between no relation things
15:46don1ruillintroducing a concept is quite fun here
15:46don1ruilland still the confusion will be made with meaning of a project
15:47don1ruillso then again design
15:47don1ruilland, software design
15:47don1ruillbtw, this make sense for me
15:47don1ruilland needs to be thought again and again before doing something wrong
15:48don1ruill:)
denvercowboy joined the room.
15:49defnullWe are watching you o__o
15:49don1ruillthat's what we are doing 8)
tools joined the room.
15:53don1ruilltests vs experiments
15:54defnullI started with libgdx instead of building the low level opengl stuff myself. Still, knowing the basics does help a lot.
15:54don1ruillLibGDX is an excellent way to understand this logic
15:58don1ruillyou are giving me the envy of doing this
15:58don1ruill:)
15:58don1ruillto experiments thos tick and fps
15:58defnullYou are committing bibary files ...
15:58defnullbinary
15:58defnullthe jar file
15:58defnullStoooop :D
15:59don1ruillstarred
diagram joined the room.
16:00defnullheresy ;)
16:01don1ruillthank you @chubz
16:03don1ruilli am installing IntelliJ IDEA
vogdev joined the room.
16:04don1ruillyeah but i am lost when Android passed to this editor
16:04don1ruillso must learn this before
16:04don1ruillwith eclipse it was fine
16:04don1ruillthen now it's completely groovy
16:04don1ruilli mean psychedelic :D
sonhiikari joined the room.
rauko joined the room.
16:05don1ruilli don't know if a fork is better here
16:05don1ruill:/
parbey joined the room.
16:06don1ruillexactly
16:07don1ruillyes i see this also like a scratch think from where you start something
16:08don1ruillvoila
16:14defnullree
marianyc joined the room.
16:16don1ruillhttp://imgur.com/3v7U4Xm
uarebugged joined the room.
nagibauvsex joined the room.
16:17chubz-Djava.library.path=native/
16:17don1ruillok
16:18don1ruilli do it
16:18don1ruillthx
16:19don1ruilli have seen this one day on Livecoding.TV
16:19don1ruillhere it is, i think it's the second tutorial
16:19don1ruillhttps://www.youtube.com/user/Profyx
16:21don1ruilli am trying to do it
16:22don1ruillgoing to take a tee cup and i am back
16:22don1ruillto see ho i can run it locally
16:22don1ruill*how
studentprogrammer joined the room.
16:24studentprogr...very well hope everythong is going good
pokerdj joined the room.
instalockgg joined the room.
16:29don1ruillhttp://imgur.com/DBa58mE
defnull joined the room.
hajdam joined the room.
16:35don1ruillhttp://imgur.com/D0MuNFN
16:35don1ruillseems the SDK is not defined now
16:35don1ruillok
rothien joined the room.
tesleax joined the room.
16:36chubz-Djava.library.path=native/
16:37don1ruillthx
16:37don1ruillhttp://imgur.com/9VfKAov
16:38don1ruilli am setuping the SDK
16:38don1ruillok
16:38chubzC:\Program Files\Java\jdk1.8.0_66
16:41don1ruillhttp://imgur.com/M1rYDei
16:41don1ruillin doing
16:41don1ruill:)
16:43don1ruillhttp://imgur.com/KJ5VcjE
16:43tesleaxdont choose bin
16:44don1ruillah ok
16:44tesleax60 fps ? :d
16:45tesleaxi dont think so,
16:45don1ruillit works !
16:45don1ruillhttp://imgur.com/AmLcfVs
16:45don1ruill:)
16:45tesleaxgood
16:47don1ruillyes
16:47don1ruillit's again the configuration
16:47don1ruillhttp://imgur.com/fQw7cl7
16:48chubz-Djava.library.path=native/
zhipeng joined the room.
16:48don1ruillok
16:50tesleaxoh i see
16:50tesleaxit is a huge performance decrease
16:53don1ruillhttp://imgur.com/jeNu4kS
16:54don1ruill:good:
douzifly joined the room.
phanxgames joined the room.
vagarlee joined the room.
guoziyan joined the room.
zhoot joined the room.
kjbeaulieu joined the room.
glassc1ph3r joined the room.
17:02don1ruillit's the module issue now
rogerthat joined the room.
17:06don1ruillhttp://imgur.com/8LsqW00
mikewagner joined the room.
th3darkzi0n joined the room.
isabella joined the room.
nadweniro joined the room.
pharmasolin joined the room.
17:14don1ruillhttp://imgur.com/U3DWSNV
17:14don1ruillhere i am
```

rogerthat joined the room.
livecodingtv_support joined the room.
17:15chubz-Djava.library.path=native/
17:15don1ruillok
redpanda joined the room.
17:16don1ruilli do
17:18don1ruillmeanwhile, i am confused here
17:19don1ruilli am going to open an issue here
17:20don1ruillcheck me on github

:100:

**Comment by MightyChubz** [comment]
Hello, don1ruill, this issue tends to occur when the Path to the native folder is incorrectly put in. Please copy and paste this with space included, “ -Djava.library.path=native/”. This should fix the issue, please, if the issue prosiest tell me. (sorry for the mess up there)

**Comment by nazimboudeffa** [comment]
Thank you @MightyChubz here what i get in french for the moment :1234: 

"C:\Program Files\Java\jdk1.7.0_79\bin\java" Djava.library.path=native/ -Didea.launcher.port=7542 "-Didea.launcher.bin.path=C:\Program Files (x86)\JetBrains\IntelliJ IDEA Community Editio

Erreur : impossible de trouver ou charger la classe principale Djava.library.path=native.

Process finished with exit code 1
:

**Comment by MightyChubz** [comment]
Sorry for this writing error I made, “ -Djava.library.path=native/”, sorry for the writing issue. If this doesn’t work, please go to this link [here](http://wiki.lwjgl.org/wiki/Setting_Up_LWJGL_with_IntelliJ_IDEA). Another issue could be that you are using Java 1.7 when the engine uses 1.8. It is highly recommended that you get the latest version of Java [here](http://www.oracle.com/technetwork/java/javase/downloads/index.html).

**Comment by ghost** [comment]
interesting :8ball: 

i am finding this error now 

Exception in thread "Main" java.lang.UnsatisfiedLinkError: no lwjgl in java.library.path
    at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1886)
    at java.lang.Runtime.loadLibrary0(Runtime.java:849)
    at java.lang.System.loadLibrary(System.java:1088)
    at org.lwjgl.system.Library.loadSystem(Library.java:97)
    at org.lwjgl.system.Library.<clinit>(Library.java:48)
    at org.lwjgl.system.MemoryAccess.<clinit>(MemoryAccess.java:22)
    at org.lwjgl.system.Pointer.<clinit>(Pointer.java:22)
    at org.lwjgl.glfw.GLFW.<clinit>(GLFW.java:594)
    at com.MightyChubz.core.Main.load(Main.java:88)
    at com.MightyChubz.core.Main.run(Main.java:42)
    at java.lang.Thread.run(Thread.java:745)

Process finished with exit code 0

**Comment by deeegroovy** [comment]
seems it's the same error like the first one in the chat

**Comment by nazimboudeffa** [comment]
seems like it's the same error like the first one in the chat :1234:

**Comment by MightyChubz** [comment]
Please wait while I fix this.

**Comment by nazimboudeffa** [comment]
:+1:

**Comment by MightyChubz** [comment]
Please pull the latest update and read the PDF, “Issue with path”. This should fix it.

**Comment by MightyChubz** [comment]
If it doesn't search for tutorial on setting up LWJGL in IDEA.

**Comment by MightyChubz** [comment]
As of right now, this issue has been fixed and the project has been updated with a detailed PDF file to help people start using this project. If an issue occur relating around Java.library.path and all steps with the PDF didn’t work, please tell me.
